### ISSUE TITLE
Expose open_dir and read_dir from FATFS(or make MOS calls for this)

### ISSUE THREAD

**Issue by nihirash** [breakintoprogram/agon-mos#72] opened 2023-06-20 11:39 UTC
Currently, we have no possibility read directory from applications(for example, for making file managers, CP/M emulation layer or something like this). 

I'd like get FatFS or MOS API for reading directory.

**Comment by breakintoprogram** [comment] 2023-06-27 16:27
Closing this card as it is a duplicate of #52

**Closed** 2023-06-27 16:27 UTC
Labels: duplicate
