### ISSUE TITLE
mos_fclose not usable if VDP in terminal mode

### ISSUE THREAD

**Issue by nihirash** [breakintoprogram/agon-mos#69] opened 2023-06-05 17:46 UTC
It tries fetch RTC data but have no possibility.

Please add flag to ignore RTC data - cause my CP/M implementation working in terminal mode and there no RTC data.

**Comment by leighbb** [comment] 2023-06-12 15:43
I don't the history around some of the design choices. Having said that, would it not be better to switch to using the ez80 RTC for this stuff?

**Comment by leighbb** [comment] 2023-06-13 13:32
I think there is still room for a "raw" Terminal approach, but I think it is a bit limiting. I would prefer an approach that allows you to use user defined terminal sequences to achieve the same functionality when operating in Terminal mode.  There may still be a part to play for a completely "raw" terminal mode, but I think an approach that still allows you to use the full MOS functionality would be better.

I'll share a rough outline of the approach when I get a chance. I have it more or less working, but need to tidy it up.

**Comment by nihirash** [comment] 2023-06-13 13:43
This patch mainly required for CP/M. In MOS mode there no requirements for this.

**Comment by sijnstra** [comment] 2023-06-21 10:46
Not just required to CP/M mode. I've converted my infocom interpreter to use terminal mode to have access to 80 columns and underline in the font, as well as other VT100 functionality. Now I can't save games as that required the datestamp for file creation.

**Comment by nihirash** [comment] 2023-06-21 11:20
As adhoc solution - you can grab MOS binary from cp/m chat in discord - it's vanilla MOS with my simple patch.

**Comment by sijnstra** [comment] 2023-06-24 23:17
I ended up compiling from your fork - I have to justify buying that zilog cable somehow! Anyway, confirmed that it's working and solved my issue with creating new files while in terminal mode. This patch allowed me to confidently release my infocom interpreter, however, I am absolutely happy to change my code if a different agreed method for getting around this issue turns up.

**Comment by nihirash** [comment] 2023-06-25 12:20
You can flash it just via https://github.com/envenomator/agon-flash

If something will go wrong - you can flash Agon HAL firmware for ESP with support uploading flash via USB and when computer starts successfully rollback to Quark

**Comment by breakintoprogram** [comment] 2023-07-08 17:58
Closing as 'Won't Do' as this is a duplicate of #70.

**Closed by breakintoprogram** 2023-07-08 17:58 UTC
Labels: enhancement
